#!/bin/bash
# Set up ESPHome dev environment

set -e

cd "$(dirname "$0")/.."
pip3 install -r requirements.txt -r requirements_optional.txt -r requirements_test.txt
sudo pip3 install -e .

pre-commit install
